version: '3.4'

services:
  mongo:
    image: mongo:4.4.10
    ports:
      - "27017:27017"
    volumes:
      - /home/vpiska/data/mongo:/data/db

  api:
    image: api
    environment:
      - SERVER_PORT=5000
      - DB_CONNECTION=mongodb://mongo:27017
      - DB_NAME=vpiska
      - JWT_KEY=vpiska_secretkey!123
      - JWT_ISSUER=VpiskaServer
      - JWT_AUDIENCE=VpiskaClient
      - JWT_LIFETIME_DAYS=3
      - HASH_KEY=fbac497e4b44564f831f78d539b81a0c
    ports:
      - "5000:5000"
    volumes:
      - /home/vpiska/data/media:/app/media
      - /home/vpiska/data/logs:/app/logs
    build:
      context: .
      dockerfile: ./Dockerfile