basePath: /api/v1
definitions:
  github.com_iamsorryprincess_vpiska-backend-go_internal_delivery_http_v1.apiResponse:
    properties:
      errors:
        items:
          $ref: '#/definitions/github.com_iamsorryprincess_vpiska-backend-go_internal_delivery_http_v1.errorResponse'
        type: array
      isSuccess:
        type: boolean
      result: {}
    type: object
  github.com_iamsorryprincess_vpiska-backend-go_internal_delivery_http_v1.changePasswordRequest:
    properties:
      confirmPassword:
        type: string
      id:
        type: string
      password:
        type: string
    type: object
  github.com_iamsorryprincess_vpiska-backend-go_internal_delivery_http_v1.createUserRequest:
    properties:
      confirmPassword:
        type: string
      name:
        type: string
      password:
        type: string
      phone:
        type: string
    type: object
  github.com_iamsorryprincess_vpiska-backend-go_internal_delivery_http_v1.errorResponse:
    properties:
      errorCode:
        type: string
    type: object
  github.com_iamsorryprincess_vpiska-backend-go_internal_delivery_http_v1.loginResponse:
    properties:
      accessToken:
        type: string
      id:
        type: string
      imageId:
        type: string
      name:
        type: string
      phone:
        type: string
    type: object
  github.com_iamsorryprincess_vpiska-backend-go_internal_delivery_http_v1.loginUserRequest:
    properties:
      password:
        type: string
      phone:
        type: string
    type: object
  internal_delivery_http_v1.apiResponse:
    properties:
      errors:
        items:
          $ref: '#/definitions/internal_delivery_http_v1.errorResponse'
        type: array
      isSuccess:
        type: boolean
      result: {}
    type: object
  internal_delivery_http_v1.changePasswordRequest:
    properties:
      confirmPassword:
        type: string
      id:
        type: string
      password:
        type: string
    type: object
  internal_delivery_http_v1.createUserRequest:
    properties:
      confirmPassword:
        type: string
      name:
        type: string
      password:
        type: string
      phone:
        type: string
    type: object
  internal_delivery_http_v1.errorResponse:
    properties:
      errorCode:
        type: string
    type: object
  internal_delivery_http_v1.loginResponse:
    properties:
      accessToken:
        type: string
      id:
        type: string
      imageId:
        type: string
      name:
        type: string
      phone:
        type: string
    type: object
  internal_delivery_http_v1.loginUserRequest:
    properties:
      password:
        type: string
      phone:
        type: string
    type: object
info:
  contact: {}
  description: API vpiska.ru
  title: Swagger UI
  version: "1.0"
paths:
  /users/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_delivery_http_v1.createUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/internal_delivery_http_v1.apiResponse'
            - properties:
                result:
                  $ref: '#/definitions/internal_delivery_http_v1.loginResponse'
              type: object
      summary: Создать пользователя
      tags:
      - users
  /users/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_delivery_http_v1.loginUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/internal_delivery_http_v1.apiResponse'
            - properties:
                result:
                  $ref: '#/definitions/internal_delivery_http_v1.loginResponse'
              type: object
      summary: Войти в систему
      tags:
      - users
  /users/password/change:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_delivery_http_v1.changePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/internal_delivery_http_v1.apiResponse'
            - properties:
                result:
                  $ref: '#/definitions/internal_delivery_http_v1.loginResponse'
              type: object
      summary: Изменить пароль
      tags:
      - users
swagger: "2.0"
