basePath: /api
definitions:
  v1.apiResponse:
    properties:
      errors:
        items:
          $ref: '#/definitions/v1.errorResponse'
        type: array
      isSuccess:
        type: boolean
      result: {}
    type: object
  v1.changePasswordRequest:
    properties:
      confirmPassword:
        type: string
      password:
        type: string
    type: object
  v1.createUserRequest:
    properties:
      confirmPassword:
        type: string
      name:
        type: string
      password:
        type: string
      phone:
        type: string
    type: object
  v1.errorResponse:
    properties:
      errorCode:
        type: string
    type: object
  v1.fileMetadataResponse:
    properties:
      contentType:
        type: string
      id:
        type: string
      name:
        type: string
      size:
        type: integer
    type: object
  v1.loginResponse:
    properties:
      accessToken:
        type: string
      id:
        type: string
      imageId:
        type: string
      name:
        type: string
      phone:
        type: string
    type: object
  v1.loginUserRequest:
    properties:
      password:
        type: string
      phone:
        type: string
    type: object
info:
  contact: {}
  description: API vpiska.ru
  title: Swagger UI
  version: "1.0"
paths:
  /v1/media:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/v1.apiResponse'
            - properties:
                result:
                  type: string
              type: object
      summary: Загрузить медиафайл
      tags:
      - media
  /v1/media/{id}:
    get:
      consumes:
      - '*/*'
      parameters:
      - description: media ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: ""
        "400":
          description: ""
        "404":
          description: ""
      summary: Получить медиафайл
      tags:
      - media
  /v1/media/metadata/{id}:
    get:
      consumes:
      - '*/*'
      parameters:
      - description: media ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/v1.apiResponse'
            - properties:
                result:
                  $ref: '#/definitions/v1.fileMetadataResponse'
              type: object
      summary: Получить метаинформацию о файле
      tags:
      - media
  /v1/users/create:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.createUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/v1.apiResponse'
            - properties:
                result:
                  $ref: '#/definitions/v1.loginResponse'
              type: object
      summary: Создать пользователя
      tags:
      - users
  /v1/users/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.loginUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/v1.apiResponse'
            - properties:
                result:
                  $ref: '#/definitions/v1.loginResponse'
              type: object
      summary: Войти в систему
      tags:
      - users
  /v1/users/password/change:
    post:
      consumes:
      - application/json
      parameters:
      - description: body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/v1.changePasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/v1.apiResponse'
            - properties:
                result:
                  $ref: '#/definitions/v1.loginResponse'
              type: object
      security:
      - UserAuth: []
      summary: Изменить пароль
      tags:
      - users
securityDefinitions:
  UserAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
