name: build-deploy
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: [self-hosted, linux, X64]
    steps:
      - uses: actions/checkout@v2
      - name: build
        run: docker-compose build api
      - name: deploy
        run: docker service update --force lt8b8lng49j6